### ISSUE TITLE
Research the best design approach for regular user/organizer/admin signup

### ISSUE THREAD

**Issue by shonore** [Syna3C/Syna3C-Project#12]
Option 1: All users sign up through a single portal. They are all regular users initially and their role can be altered via the admin dashboard. To be an organizer, the user would have to provider the required fields (org name, org address, org phone #, etc) through the settings page. 

Option 2: There is a separate signup form for organizer role. The user would enter the required information here

**Comment by maeutic** [comment]
My inclination would be for Option 2, since it minimizes the need for constant hands on interaction by admins. The flagging feature & tech contact should allow users to notify admins if they think an organizer account is fraudulently representing an organization. Another question for Geoff.

Far down the road we might look at a Guidestar API access to help verify organizer status, but until there's a solid fundraising plan that's out of reach financially.

**Comment by shonore** [comment]
We are going to wait for the Drupal site to go live so we can get a better understanding of the login/signup flow. We can get a better understanding of the signup logic then

**Comment by shonore** [comment]
Mac got Drupal POC is live, we are just waiting to get the core updated. It cannot be public until the core is updated. Once it is public we can look at the POC
